### ISSUE TITLE
MyndraineHN font fails

### ISSUE THREAD

**Issue by jay-ramani** [Magisk-Modules-Repo/Fontchanger#15]
Hi John,

While installing the font from the downloadable list, the Myndraine Large font gets applied, but font_changer fails to apply the MyndraineHN font. Tested on two different devices with different ROMs [Poco F1 on Resurrection Remix (Pie based), and OnePlus One (A0001) on MSM Xtended XQ Release v6 (Q based)].

Would be great if you could fix this.

Thanks,
Jay

**Comment by JohnFawkes** [comment]
Fixed

**Comment by jay-ramani** [comment]
John, applying the MyndraineHN font fails (tested on both devices mentioned above) on the latest version (3.0.0.3) of your script on Magisk. Looks like you haven't propagated the fix, or this bug is still not fixed. Either way, can you try applying the font yourself from Magisk Manager (from a user's perspective)? See the attached pictures for details.

Let me know if you need help with logs.

Thanks,
Jay
![Screenshot_20200319-031122_Termux](https://user-images.githubusercontent.com/7327430/77041484-60e44080-6990-11ea-9b78-4a919601a976.png)
![Screenshot_20200319-031236_Termux](https://user-images.githubusercontent.com/7327430/77041486-617cd700-6990-11ea-8813-dbb2c28a12d3.png)

**Comment by JohnFawkes** [comment]
I did test it and just tested again. Works fine
![Screenshot_20200319-050542](https://user-images.githubusercontent.com/33303104/77049954-5aa99080-699f-11ea-9b79-86a8d401bfcc.jpg)

**Comment by JohnFawkes** [comment]
Try going to internal storage/Fontchanger/Fonts and finding the mydrainehn zip and deleting it and trying again

**Comment by jay-ramani** [comment]
Yup, deleted the file and checked again, but the issue persists. I noticed the downloaded file is only 766 bytes. I opened the file as text to discover that the error is the file cannot be found on the server. Here's the content of the downloaded file:

```
<!DOCTYPE html>
<html style="height:100%">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title> 404 Not Found
</title><script src="/cdn-cgi/apps/head/RWN5si90a3SCYfmQRWEhHv4GnqY.js"></script></head>
<body style="color: #444; margin:0;font: normal 14px/20px Arial, Helvetica, sans-serif; height:100%; background-color: #fff;">
<div style="height:auto; min-height:100%; "> <div style="text-align: center; width:800px; margin-left: -400px; position:absolute; top: 30%; left:50%;">
<h1 style="margin:0; font-size:150px; line-height:150px; font-weight:bold;">404</h1>
<h2 style="margin-top:20px;font-size: 30px;">Not Found
</h2>
<p>The resource requested could not be found on this server!</p>
</div></div></body></html>
```

Is your repository hosted at https://john-fawkes.com/Downloads/?MD? If so, every other font package in has a "Font_" prefix, except "MyndrainHN.zip". Is that the issue?

**Comment by JohnFawkes** [comment]
Not sure what the issue is. Working fine on my end. Maybe it's not
downloading the correctly and corrupting the zip?

**Comment by jay-ramani** [comment]
The file is not found by the script (same HTTP error in the 766 byte font zip file) on both my phone running different versions of Android (Pie on a Poco F1 and Q on the OnePlus One). There's no corruption.

```
 <h2 style="margin-top:20px;font-size: 30px;">Not Found
 </h2>
 <p>The resource requested could not be found on this server!</p>
 </div></div></body></html>
```

Happening only with this font, everything else works. That's why I'm suspecting "Font_" not being prefixed with the MyndraineHN font's zip file on your server.

**Comment by JohnFawkes** [comment]
I already fixed it on my server. You'll need to delete the zip and try
again. Works just fine on my device

**Comment by jay-ramani** [comment]
I see you have changed the name of MyndraineHN.zip on your server by prefixing it with "Font_".

It's working now; have verified on both my phones. So that was the issue.
